# Generated by Django 6.0.1 on 2026-02-17 14:45

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('job_number', models.CharField(help_text='Format: 111XXXXXXX for EMEA, 222XXXXXXX for APAC, etc.', max_length=10, unique=True)),
                ('client_name', models.CharField(max_length=200)),
                ('region', models.CharField(choices=[('EMEA', 'EMEA'), ('APAC', 'APAC'), ('NA', 'NA'), ('LATAM', 'LATAM')], max_length=10)),
                ('description', models.TextField(blank=True, null=True)),
                ('expected_work_hours', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('project_status', models.CharField(choices=[('ACTIVE', 'ACTIVE'), ('PENDING', 'PENDING'), ('COMPLETED', 'COMPLETED')], default='PENDING', max_length=10)),
                ('assigned_employees', models.ManyToManyField(blank=True, related_name='projects', to='accounts.employee')),
                ('project_manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_projects', to='accounts.employee')),
            ],
        ),
    ]
