# Generated by Django 6.0.1 on 2026-02-20 17:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('projects', '0002_project_created_at_project_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=150)),
                ('date', models.DateField(help_text='The day the work was performed')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hours_worked', models.DecimalField(decimal_places=2, help_text='Total time spent on the task', max_digits=4)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='accounts.employee')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='projects.project')),
            ],
            options={
                'verbose_name_plural': 'Activities',
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
