# Generated by Django 6.0.1 on 2026-02-15 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('job_title', models.CharField(max_length=50)),
                ('department', models.CharField(choices=[('ADMIN', 'ADMIN'), ('HR', 'HR'), ('SALES', 'SALES'), ('MARKETING', 'MARKETING'), ('FINANCE', 'FINANCE'), ('IT', 'IT'), ('OTHER', 'OTHER')], default='OTHER', max_length=15)),
                ('date_joined', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
